name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tf:1.10
    - name: Run
      run: docker run -it --rm --entrypoint '' tf:1.10 ls /usr/share/terraform/providers
      
